### ISSUE TITLE
grpcio pin inside the recipe

### ISSUE THREAD

**Issue by yinweisu** [conda-forge/ray-packages-feedstock#109]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I found there's a grpcio pin inside the [recipe](https://github.com/conda-forge/ray-packages-feedstock/blob/main/recipe/meta.yaml#L85), which doesn't match what's being specified in ray's setup.py. This pin will stop conda user install latest version of ray alongside with latest version of tensorflow, as there's a version conflicts in grpcio. It would be great if we can align this grpcio pin to setup.py in ray

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by richardliaw** [comment]
@mattip is this something you could look into?

**Comment by yinweisu** [comment]
@richardliaw Thank you so much! This is very important to us, and it would be great if we can solve this ASAP

**Comment by mattip** [comment]
See #98 (specifically [this comment](https://github.com/conda-forge/ray-packages-feedstock/pull/98#issuecomment-1555309701)) which led to issue #109 and ray-project/ray#35383. I think there may be some conflict with the [grpcio 1.46.6 ray vendors into its bazel build](https://github.com/ray-project/ray/blob/44cfe47113e89676457d5c5d34597c72d10db930/bazel/ray_deps_setup.bzl#L235), and that internal version apparently conflicts with the conda-provided 1.50+

**Comment by yinweisu** [comment]
So if I understand it correctly, the conda version of grpcio>1.50.0 is somehow different from what's being offered by pypi causing conda version of ray to fail? This issue is known, but not a clear path forward has been decided yet.

**Comment by mattip** [comment]
Yes, I think that is a fair assessment of the situation. It is not clear where to expand effort: moving ray to use a newer grpcio internally, or debugging why on all of conda-forge only the ray feedstock seems to need this `<1.50` pin.

**Comment by yinweisu** [comment]
@mattip Thanks for the explanation.
@richardliaw Does ray team have any plan regarding this? It's definitely not a long term solution to keep an obsolete pin. I believe there are security vulnerabilities presented in older versions of grpcio too. This could be a big obstacle to many service teams that want to integrate ray

**Comment by richardliaw** [comment]
By the way, in 2.7 ray is not going to need grpc by default; believe
@zhe-thoughts will have more details

**Comment by h-vetinari** [comment]
The proper solution would be https://github.com/conda-forge/ray-packages-feedstock/issues/90, i.e. do not vendor protobuf & grpc (or at least provide an opt-out in the ray build that we could use). Unfortunately, it's just so absurdly complicated to actually point to existing artefacts with bazel that I have not mustered the energy to jump down this rabbit hole.

Regarding failures in grpc, as soon as someone reproduces this, we'll try to get it fixed. I tried to switch on the C++ testing for grpc [recently](https://github.com/conda-forge/grpc-cpp-feedstock/pull/311), but it doesn't even compile (filed an upstream bug; will take a while to get this going I think).

**Comment by mattip** [comment]
Here is what I had in [PR #98](https://github.com/conda-forge/ray-packages-feedstock/pull/98#issuecomment-1557040916) as a minimal reproducer:

```
$ mamba create -n throw-away1 python=3.9 ray-serve=2.4.0
$ conda activate throw-away1
$ python -c "import ray; ray.init()"
# succeeds
$ mamba install --no-deps grpcio=1.51.1 libgrpc=1.51.1 grpc-cpp=1.51.1
$ python -c "import ray; ray.init()"
# fails

$ mamba create -n throw-away2 python=3.9 ray-serve=2.4.0
$ conda activate throw-away2
$ python -c "import ray; ray.init()"
# succeeds
$ pip install grpcio==1.51.1
$ python -c "import ray; ray.init()"
# succeeds
```

Or maybe you were referring to something else?

**Comment by yinweisu** [comment]
@richardliaw Thanks for the info. Any timeline on when 2.7 will be out?

**Comment by h-vetinari** [comment]
Sorry, I misspoke (it was late...) - I meant a root cause rather than a reproducer. If we can point to a concrete problem in grpc, abseil, protobuf or whatever, we can try to get this fixed in the packaging or with the respective upstream maintainers.

**Comment by yinweisu** [comment]
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/throw-away1/lib/python3.9/site-packages/ray/__init__.py", line 109, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 119, in init ray._raylet
  File "/opt/conda/envs/throw-away1/lib/python3.9/site-packages/ray/exceptions.py", line 17, in <module>
    from ray.util.annotations import DeveloperAPI, PublicAPI
  File "/opt/conda/envs/throw-away1/lib/python3.9/site-packages/ray/util/__init__.py", line 5, in <module>
    from ray._private.services import get_node_ip_address
  File "/opt/conda/envs/throw-away1/lib/python3.9/site-packages/ray/_private/services.py", line 26, in <module>
    from ray._private.gcs_utils import GcsClient
  File "/opt/conda/envs/throw-away1/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 11, in <module>
    import grpc
  File "/opt/conda/envs/throw-away1/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/opt/conda/envs/throw-away1/lib/python3.9/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: libabsl_status.so.2301.0.0: cannot open shared object file: No such file or directory
```
@h-vetinari Thanks. I would like to help if we can get this unblocked. Is this stack trace enough for you to take a look on what's the problem behind?

**Comment by h-vetinari** [comment]
> @h-vetinari Thanks. I would like to help if we can get this unblocked. Is this stack trace enough for you to take a look on what's the problem behind?

That's enough for a start. Getting abseil libraries to be present isn't a big issue (if that is all there is to it). I rebased https://github.com/conda-forge/ray-packages-feedstock/pull/87 and I also opened https://github.com/conda-forge/grpc-cpp-feedstock/pull/312 (plus did some more work on https://github.com/conda-forge/grpc-cpp-feedstock/pull/311).

**Comment by h-vetinari** [comment]
So the abseil error is not present in https://github.com/conda-forge/grpc-cpp-feedstock/pull/312 nor in #87. In the latter, we're again stuck with
```
+ python -c 'import ray; ray.init(include_dashboard=True)'
2023-08-27 12:06:41,530	WARNING services.py:1832 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67104768 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=1.16gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-08-27 12:06:41,667	INFO worker.py:1621 -- Started a local Ray instance.
[2023-08-27 12:06:42,584 E 39720 39720] core_worker.cc:201: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

This is something that was [raised](https://github.com/ray-project/ray/issues/35383) with ray already a while ago. I don't know what's going on there.

**Comment by yinweisu** [comment]
@mattip I saw you created this [issue](https://github.com/ray-project/ray/issues/35383) referred by @h-vetinari. Any updates on it?

**Comment by mattip** [comment]
No updates. I do not know how to debug what seems to be failures to pass grpcio messages.

**Comment by mattip** [comment]
I think we can close this. Ray now pins to a higher version of grcpio https://github.com/conda-forge/ray-packages-feedstock/blob/818fe7824d2d7240085e9f592053fc09dfbaf913/recipe/meta.yaml#L172
