### ISSUE TITLE
Bazel pins

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/ray-packages-feedstock#34]
I just wanted to check upstream what the currently pinned/approved bazel version is, but since [it is](https://github.com/ray-project/ray/blob/ray-1.5.1/python/setup.py#L25) at 3.2.0, our pinning already violates that.

So why are we pinning bazel at all? @krfricke @vnlitvinov 
Cf. some issues in #21.

**Comment by vnlitvinov** [comment]
I have somehow missed that... Current pinning in the conda recipe was found by trial and error because some more recent Bazel versions failed the build. I do not know what's the current situation, though.

**Comment by krfricke** [comment]
I have to update the feedstock for upcoming Ray 1.7 next week anyway as we upstreamed some of the patches. I can check Bazel version compatibility then, too

**Comment by mattip** [comment]
I think this should be closed.

**Comment by mattip** [comment]
Closing. bazel is pinned like upstream now to 5.4.1
