### ISSUE TITLE
aioredis 2.x breaks Ray

### ISSUE THREAD

**Issue by vnlitvinov** [conda-forge/ray-packages-feedstock#38]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: the same pinning done in https://github.com/ray-project/ray/pull/17465 should be done in the conda-forge packages as well. Apparently packages starting from at least `ray-1.4.0` are affected.

cc @krfricke

**Comment by h-vetinari** [comment]
We do this as of https://github.com/conda-forge/ray-packages-feedstock/commit/c9f722da074a1a0120321a955440e378a416fd0b
