### ISSUE TITLE
`ray` seems to link against the wrong `libgcc`

### ISSUE THREAD

**Issue by xhochy** [conda-forge/ray-packages-feedstock#48]
The build log contains the following line:

```
2022-01-21T16:09:13.8598640Z   ERROR (ray-core,lib/python3.7/site-packages/ray/_raylet.so): $PATH/lib/libgcc_s.so.1 found in build prefix; should never happen
```

This introduces the problem that somehow running things in a ray worker triggers the use of the system `libgcc_s`:

```
ImportError: /lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by $PREFIX/lib/python3.9/site-packages/pyarrow/../../../libarrow.so.600)
```

My wild guess would be that the use of the `bazel-toolchain` would fix this.

**Comment by timkpaine** [comment]
Could be https://github.com/bazelbuild/bazel/issues/4137 again

**Comment by isuruf** [comment]
Somebody is setting `-Wl,--enable-new-dtags`. We should disable that.
