### ISSUE TITLE
Python 3.7 Build For Ray >=2.1.0

### ISSUE THREAD

**Issue by harelwa** [conda-forge/ray-packages-feedstock#86]
### Comment:

Hi,

A Python 3.7 build is no longer published for ray version >=2.1.0

- https://github.com/conda-forge/ray-packages-feedstock/tree/main/.ci_support ) - 
- https://anaconda.org/conda-forge/ray-all/files

I wanted to ask why, and if it would be possible to re-add the relevant CI support to publish py37 builds.

I'm asking because:

1. I'm using Ray in a Python 3.7 code base
2. Ray project still support Python 3.7, and publish PyPi builds accordingly ( https://pypi.org/project/ray/#files )

Thank you,
Harel

**Comment by mattip** [comment]
Python 3.7 is no longer supported by the conda-forge build system. See [the announcement](https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7)

**Comment by harelwa** [comment]
Thank you @mattip , I missed that.
