### ISSUE TITLE
Unpin `gym <0.24`

### ISSUE THREAD

**Issue by SimonBoothroyd** [conda-forge/ray-packages-feedstock#93]
### Comment:

Older versions of `gym` (<0.25.1) are incompatible with newer versions of `numpy` due to their use of `randint`. Would it be possible to remove the upper bound pin in the `rllib` recipe to allow using new versions of `gym` / `numpy`?

**Comment by h-vetinari** [comment]
This is dependent on ray upping their gym upper bound (resp. fully adapt to the switch to gymnasium). Some of this has happened for the upcoming ray 2.0, and some is in [progress](https://github.com/ray-project/ray/issues/31587)

**Comment by h-vetinari** [comment]
This should be solved as of the most recent ray 2.3 builds.
